export const project = {
  name: "Чудо Зайка",
  title: "Праздник, который начинается с улыбки",
  lead: "Аниматоры, шоу-программы и экспресс-поздравления по Владивостоку и Приморскому краю.",
  phone: "+7 (994) 994-04-33",
  phoneHref: "tel:+79949940433",
  telegram: "https://t.me/CongratulationsinPrimorye",
  region: "Владивосток и весь Приморский край",
};

export const categories = [
  {
    id: "party",
    title: "Большой праздник",
    eyebrow: "от 45 минут",
    description: "Аниматоры, игры, шоу и музыкальная программа для дня рождения, выпускного или семейного события.",
    image: "./public/media/hero.jpg",
  },
  {
    id: "express",
    title: "Экспресс-поздравление",
    eyebrow: "10–15 минут",
    description: "Эффектное появление героя, личное поздравление, танцевальный интерактив, объятия и фотографии.",
    image: "./public/media/express-group.jpg",
  },
];

export const services = [
  {
    id: "arthur-pirozhkov",
    category: "express",
    title: "Артур Пирожков",
    badge: "Звёздный хит",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/arthur.jpg",
    gallery: ["./public/media/arthur.jpg", "./public/media/express-group.jpg"],
    video: "./public/media/arthur.mp4",
    short: "Юмор, музыка и эффектное персональное поздравление от любимого артиста.",
    description: "Артур появляется неожиданно, обращается к виновнику торжества, проводит короткий танцевальный интерактив и остаётся для фотографий. Подходит для дня рождения, юбилея, свадьбы и корпоратива.",
    includes: ["эффектное появление", "персональные слова", "танцевальный интерактив", "фотографии с гостями"],
  },
  {
    id: "giant-bear",
    category: "express",
    title: "Медведь-гигант",
    badge: "3 метра",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/bear.jpg",
    gallery: ["./public/media/bear.jpg", "./public/media/bear-family.jpg"],
    short: "Огромный белый медведь для тёплого сюрприза, вручения цветов и семейных кадров.",
    description: "Медведь производит сильное первое впечатление и остаётся очень добрым героем. Можно передать ему ваш букет или подарок перед выходом.",
    includes: ["встреча и поздравление", "вручение вашего подарка", "объятия", "фотосессия"],
  },
  {
    id: "barney",
    category: "express",
    title: "Мишка Барни",
    badge: "Любимец гостей",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/barney.jpg",
    gallery: ["./public/media/barney.jpg", "./public/media/express-group.jpg"],
    short: "Пушистый коричный мишка, который танцует, обнимает и легко собирает вокруг себя всех гостей.",
    description: "Барни подходит детям и взрослым: на день рождения, выписку, свадьбу, корпоратив или просто как неожиданный знак внимания.",
    includes: ["яркий выход", "танец с гостями", "поздравление", "фото на память"],
  },
  {
    id: "pop-stars",
    category: "express",
    title: "Звёзды эстрады",
    badge: "На выбор",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/stars.jpg",
    gallery: ["./public/media/stars.jpg", "./public/media/arthur.jpg", "./public/media/express-group.jpg"],
    short: "Филипп Киркоров, Стас Михайлов, Ирина Аллегрова, Михаил Галустян и другие образы.",
    description: "Подберём героя под характер адресата: душевное поздравление, королевский выход, юмор или настоящий мини-концерт.",
    includes: ["герой на выбор", "персональное поздравление", "музыкальный выход", "фотографии"],
  },
  {
    id: "favorite-characters",
    category: "express",
    title: "Любимые герои",
    badge: "Для детей",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/characters.jpg",
    gallery: ["./public/media/characters.jpg", "./public/media/express-group.jpg", "./public/media/spider.jpg"],
    short: "Чебурашка, Лабубу, Зайка, ЛОЛ, герои мультфильмов и ещё десятки персонажей.",
    description: "Герой поздравит ребёнка лично, вручит подготовленный вами подарок и сделает много ярких фотографий.",
    includes: ["персонаж на выбор", "личное поздравление", "мини-игра или танец", "фотографии"],
  },
  {
    id: "character-party",
    category: "party",
    title: "Праздник с персонажем",
    badge: "Детский хит",
    duration: "от 60 минут",
    price: null,
    image: "./public/media/spider.jpg",
    gallery: ["./public/media/spider.jpg", "./public/media/characters.jpg", "./public/media/hero.jpg"],
    video: "./public/media/character-party.mp4",
    short: "Любимый герой ведёт игры, конкурсы и танцы, а программа подстраивается под возраст детей.",
    description: "Соберём программу вокруг любимого персонажа ребёнка и учтём площадку, возраст и количество гостей.",
    includes: ["аниматор в образе", "игры и конкурсы", "музыкальное сопровождение", "поздравление и фото"],
  },
  {
    id: "neon-show",
    category: "party",
    title: "Неоновое шоу",
    badge: "6–10 лет",
    duration: "от 60 минут",
    price: null,
    image: "./public/media/neon.jpg",
    gallery: ["./public/media/neon.jpg", "./public/media/animators.jpg"],
    short: "Светящийся реквизит, музыка, трендовые игры и яркая дискотека в темноте.",
    description: "Драйвовая программа для школьников: ведущие, танцы, игры и светящиеся эффекты, которые особенно хорошо смотрятся на фото и видео.",
    includes: ["два ярких ведущих", "неоновый реквизит", "игры и танцы", "музыкальное сопровождение"],
  },
  {
    id: "foam-party",
    category: "party",
    title: "Пенная вечеринка",
    badge: "Летний хит",
    duration: "45–60 минут",
    price: null,
    image: "./public/media/foam.jpg",
    gallery: ["./public/media/foam.jpg", "./public/media/hero.jpg"],
    short: "Море безопасной пены, музыка и активные игры во дворе, на даче или турбазе.",
    description: "Привезём оборудование и устроим настоящее облако из пены. От площадки нужен доступ к электричеству; остальные детали мы подготовим сами.",
    includes: ["пенная установка", "ведущий", "музыка", "игры в пене"],
  },
  {
    id: "bubble-show",
    category: "party",
    title: "Шоу мыльных пузырей",
    badge: "Для всей семьи",
    duration: "45–60 минут",
    price: null,
    image: "./public/media/bubbles.jpg",
    gallery: ["./public/media/bubbles.jpg", "./public/media/hero.jpg"],
    short: "Гигантские пузыри, спецэффекты и интерактив, в котором участвуют дети и взрослые.",
    description: "Лёгкое и зрелищное шоу можно провести как самостоятельную программу или добавить к празднику с аниматором.",
    includes: ["гигантские пузыри", "трюки и спецэффекты", "интерактив с гостями", "финальная фотосессия"],
  },
  {
    id: "cryo-show",
    category: "party",
    title: "Крио-шоу",
    badge: "от 5 лет",
    duration: "45–60 минут",
    price: 7500,
    image: "./public/media/cryo.jpg",
    gallery: ["./public/media/cryo.jpg", "./public/media/neon.jpg"],
    short: "Научное шоу с густым туманом, заморозкой предметов и эффектными опытами.",
    description: "Ведущий в защитной экипировке показывает опыты с жидким азотом. Дети участвуют в безопасных заданиях и наблюдают за превращениями с близкого расстояния.",
    includes: ["ведущий-учёный", "оборудование и реквизит", "серия опытов", "безопасный интерактив"],
  },
  {
    id: "graduation",
    category: "party",
    title: "Выпускной «Красочный бум»",
    badge: "Готовый пакет",
    duration: "60 минут",
    price: 35000,
    image: "./public/media/graduation.jpg",
    gallery: ["./public/media/graduation.jpg", "./public/media/animators.jpg", "./public/media/hero.jpg"],
    short: "Два ведущих, диджей, профессиональный звук и фестивальные краски для всего класса.",
    description: "Готовая программа для яркого завершения учебного года. Динамику держат два ведущих, а финалом становится общий красочный взрыв.",
    includes: ["два ведущих", "диджей и звук", "индивидуальные наборы краски", "общий яркий финал"],
  },
];

export const reviews = [
  {
    text: "Спасибо вам огромное за праздник — дочка очень рада!",
    context: "Детский день рождения",
    source: "Отзыв из Telegram-канала",
  },
  {
    text: "Дети с удовольствием участвовали в конкурсах и танцевали. Всем всё очень понравилось.",
    context: "Праздник с аниматорами",
    source: "Отзыв из Telegram-канала",
  },
  {
    text: "Спасибо огромное, вы — чудо. Мама очень счастлива и ещё долго будет вспоминать этот сюрприз.",
    context: "Поздравление с большим медведем",
    source: "Отзыв из Telegram-канала",
  },
  {
    text: "Всегда на связи, слышат и поддерживают любые идеи, создают атмосферу праздника за секунды.",
    context: "Сюрприз для подруги",
    source: "Видеоотзыв клиента",
  },
];

export const steps = [
  { number: "01", title: "Выберите формат", text: "Большая программа или короткое поздравление-сюрприз." },
  { number: "02", title: "Соберите заявку", text: "Добавьте подходящих героев и шоу в корзину." },
  { number: "03", title: "Уточним детали", text: "Свяжемся с вами, проверим дату и рассчитаем точную стоимость." },
];

export function getService(id) {
  return services.find((service) => service.id === id);
}
