export const project = {
  name: "Чудо Зайка",
  title: "Праздник, который начинается с улыбки",
  lead: "Аниматоры, шоу-программы и экспресс-поздравления по Владивостоку и Приморскому краю.",
  phone: "+7 (994) 994-04-33",
  phoneHref: "tel:+79949940433",
  telegram: "https://t.me/CongratulationsinPrimorye",
  region: "Владивосток и весь Приморский край",
};

export const categories = [
  {
    id: "animators",
    navTitle: "Герои",
    title: "Аниматоры и персонажи",
    eyebrow: "30+ образов",
    description: "Любимый герой проводит полноценную игровую программу: конкурсы, танцы, квесты и поздравление.",
    image: "./public/media/hero-lol.jpg",
  },
  {
    id: "express",
    navTitle: "Экспресс",
    title: "Экспресс-поздравление",
    eyebrow: "10–15 минут",
    description: "Артур Пирожков, Стас Михайлов, Лобода, горилла, медведи, Лабубу и другие герои для короткого сюрприза.",
    image: "./public/media/express-group.jpg",
  },
  {
    id: "shows",
    navTitle: "Шоу",
    title: "Шоу-программы",
    eyebrow: "10+ вариантов",
    description: "Пена, неон, серебряная дискотека, крио, пузыри, поролон, шары и другие самостоятельные шоу.",
    image: "./public/media/neon-show.jpg",
  },
  {
    id: "programs",
    navTitle: "Пакеты",
    title: "Готовые программы",
    eyebrow: "под событие",
    description: "Выпускные, сезонные программы и большие праздники с ведущими, диджеем и выбранным шоу.",
    image: "./public/media/graduation.jpg",
  },
];

export const catalogGroups = {
  animators: [
    {
      title: "Мультгерои",
      image: "./public/media/three-cats.jpg",
      items: ["Симка", "Нолик", "Роза Барбоскина", "Маршал", "Гонщик", "Коржик", "Карамелька", "Розочка", "Искорка", "Тучка", "Кеша", "Свинка Пеппа", "Лунтик", "Молния МакКуин", "Робокар Поли"],
    },
    {
      title: "Супергерои",
      image: "./public/media/spider.jpg",
      items: ["Леди Баг", "Алет", "Кетбой", "Человек-паук", "Чёрная Пантера", "Оптимус Прайм", "Бамблби"],
    },
    {
      title: "Сказочные и игровые",
      image: "./public/media/hero-lol.jpg",
      items: ["Эльза", "LOL Pranksta", "LOL Queen Bee", "Миньон", "Пираты", "Клоуниха Лёля", "Розовая Зайка"],
    },
    {
      title: "Ростовые куклы",
      image: "./public/media/express-group.jpg",
      items: ["Чебурашка", "Лабубу", "Маша и Медведь", "Том и Джерри", "Гарфилд", "Тигрица", "Гонщик", "Лунтик", "Кукла LOL", "Хрюшка 18+"],
    },
  ],
  express: [
    {
      title: "Звёзды эстрады",
      image: "./public/media/stars.jpg",
      items: ["Артур Пирожков", "Стас Михайлов", "Лобода", "Филипп Киркоров", "Ирина Аллегрова", "Михаил Галустян", "Влад А4", "Инстасамка"],
    },
    {
      title: "Гиганты",
      image: "./public/media/express-group.jpg",
      items: ["Мишка Барни — 3 м", "Мишка Пломбир / Снежок — 2,6 м", "Блестящий мишка", "Горилла / Кинг-Конг"],
    },
    {
      title: "Любимчики",
      image: "./public/media/labubu.jpg",
      items: ["Чебурашка", "Лабубу", "Розовая Зайка", "Кукла LOL", "Гонщик", "Милые котята"],
    },
  ],
};

export const services = [
  {
    id: "arthur-pirozhkov",
    category: "express",
    title: "Артур Пирожков",
    badge: "Звёздный хит",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/arthur.jpg",
    gallery: ["./public/media/arthur.jpg", "./public/media/express-group.jpg"],
    video: "./public/media/arthur.mp4",
    short: "Юмор, музыка и эффектное персональное поздравление от любимого артиста.",
    description: "Артур появляется неожиданно, обращается к виновнику торжества, проводит короткий танцевальный интерактив и остаётся для фотографий. Подходит для дня рождения, юбилея, свадьбы и корпоратива.",
    includes: ["эффектное появление", "персональные слова", "танцевальный интерактив", "фотографии с гостями"],
  },
  {
    id: "giant-bear",
    category: "express",
    title: "Медведь-гигант",
    badge: "3 метра",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/bear.jpg",
    gallery: ["./public/media/bear.jpg", "./public/media/bear-family.jpg"],
    short: "Огромный белый медведь для тёплого сюрприза, вручения цветов и семейных кадров.",
    description: "Медведь производит сильное первое впечатление и остаётся очень добрым героем. Можно передать ему ваш букет или подарок перед выходом.",
    includes: ["встреча и поздравление", "вручение вашего подарка", "объятия", "фотосессия"],
  },
  {
    id: "stas-mikhailov",
    category: "express",
    title: "Стас Михайлов",
    badge: "Звёздный выход",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/stas.jpg",
    gallery: ["./public/media/stas.jpg", "./public/media/stars.jpg"],
    short: "Душевное музыкальное поздравление, танец с гостями и фотографии на память.",
    description: "Шаржевый образ Стаса Михайлова приезжает с соведущим, устраивает эффектный выход и персонально поздравляет адресата.",
    includes: ["герой и соведущий", "музыкальный выход", "личное поздравление", "фотосессия"],
  },
  {
    id: "loboda",
    category: "express",
    title: "Лобода",
    badge: "Для яркой вечеринки",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/stars.jpg",
    gallery: ["./public/media/stars.jpg", "./public/media/express-group.jpg"],
    short: "Энергичный звёздный образ для музыкального поздравления и танцевального сюрприза.",
    description: "Лобода появляется под узнаваемую музыку, поздравляет виновника торжества и помогает быстро раскачать гостей.",
    includes: ["герой и соведущий", "эффектное появление", "танцевальный интерактив", "фотографии"],
  },
  {
    id: "gorilla",
    category: "express",
    title: "Горилла / Кинг-Конг",
    badge: "Максимум вау",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/gorilla.jpg",
    gallery: ["./public/media/gorilla.jpg", "./public/media/express-group.jpg"],
    short: "Огромный харизматичный герой для смешного и эффектного сюрприза детям и взрослым.",
    description: "Горилла приезжает с профессиональным соведущим, поздравляет, танцует и остаётся для общей фотосессии.",
    includes: ["горилла и соведущий", "музыкальный выход", "объятия и танец", "фотосессия"],
  },
  {
    id: "labubu-express",
    category: "express",
    title: "Лабубу",
    badge: "Хит сезона",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/labubu.jpg",
    gallery: ["./public/media/labubu.jpg", "./public/media/express-group.jpg"],
    short: "Популярный ростовой герой, музыка, танцы, поздравление и много объятий.",
    description: "Лабубу подходит для короткого поздравления ребёнка дома, на площадке или в детском центре.",
    includes: ["Лабубу и соведущий", "танцевальный выход", "поздравление", "фотосессия"],
  },
  {
    id: "cheburashka-express",
    category: "express",
    title: "Чебурашка",
    badge: "Апельсиновое безумие",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/cheburashka.jpg",
    gallery: ["./public/media/cheburashka.jpg", "./public/media/express-group.jpg"],
    short: "Танцевальный сюрприз с самым добрым героем, поздравлением и фотографиями.",
    description: "Чебурашка появляется неожиданно, проводит короткий танцевальный баттл и лично поздравляет ребёнка.",
    includes: ["Чебурашка и соведущий", "музыка и танец", "поздравление", "обнимашки и фото"],
  },
  {
    id: "barney",
    category: "express",
    title: "Мишка Барни",
    badge: "Любимец гостей",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/barney.jpg",
    gallery: ["./public/media/barney.jpg", "./public/media/express-group.jpg"],
    short: "Пушистый коричный мишка, который танцует, обнимает и легко собирает вокруг себя всех гостей.",
    description: "Барни подходит детям и взрослым: на день рождения, выписку, свадьбу, корпоратив или просто как неожиданный знак внимания.",
    includes: ["яркий выход", "танец с гостями", "поздравление", "фото на память"],
  },
  {
    id: "pop-stars",
    category: "express",
    title: "Звёзды эстрады",
    badge: "На выбор",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/stars.jpg",
    gallery: ["./public/media/stars.jpg", "./public/media/arthur.jpg", "./public/media/express-group.jpg"],
    short: "Филипп Киркоров, Стас Михайлов, Лобода, Ирина Аллегрова, Михаил Галустян и другие образы.",
    description: "Подберём героя под характер адресата: душевное поздравление, королевский выход, юмор или настоящий мини-концерт.",
    includes: ["герой на выбор", "персональное поздравление", "музыкальный выход", "фотографии"],
  },
  {
    id: "favorite-characters",
    category: "express",
    title: "Любимые герои",
    badge: "Для детей",
    duration: "10–15 минут",
    price: 5000,
    image: "./public/media/labubu.jpg",
    gallery: ["./public/media/labubu.jpg", "./public/media/express-group.jpg", "./public/media/cheburashka.jpg"],
    short: "Чебурашка, Лабубу, Зайка, ЛОЛ, герои мультфильмов и ещё десятки персонажей.",
    description: "Герой поздравит ребёнка лично, вручит подготовленный вами подарок и сделает много ярких фотографий.",
    includes: ["персонаж на выбор", "личное поздравление", "мини-игра или танец", "фотографии"],
  },
  {
    id: "character-party",
    category: "animators",
    title: "Праздник с персонажем",
    badge: "Детский хит",
    duration: "от 60 минут",
    price: null,
    image: "./public/media/spider.jpg",
    gallery: ["./public/media/spider.jpg", "./public/media/characters.jpg", "./public/media/hero.jpg"],
    video: "./public/media/character-party.mp4",
    short: "Любимый герой ведёт игры, конкурсы и танцы, а программа подстраивается под возраст детей.",
    description: "Соберём программу вокруг любимого персонажа ребёнка и учтём площадку, возраст и количество гостей.",
    includes: ["аниматор в образе", "игры и конкурсы", "музыкальное сопровождение", "поздравление и фото"],
  },
  {
    id: "neon-show",
    category: "shows",
    title: "Неоновое шоу",
    badge: "6–10 лет",
    duration: "от 60 минут",
    price: null,
    image: "./public/media/neon-show.jpg",
    gallery: ["./public/media/neon-show.jpg", "./public/media/neon.jpg"],
    short: "Светящийся реквизит, музыка, трендовые игры и яркая дискотека в темноте.",
    description: "Драйвовая программа для школьников: ведущие, танцы, игры и светящиеся эффекты, которые особенно хорошо смотрятся на фото и видео.",
    includes: ["два ярких ведущих", "неоновый реквизит", "игры и танцы", "музыкальное сопровождение"],
  },
  {
    id: "foam-party",
    category: "shows",
    title: "Пенная вечеринка",
    badge: "Летний хит",
    duration: "45–60 минут",
    price: null,
    image: "./public/media/foam.jpg",
    gallery: ["./public/media/foam.jpg", "./public/media/hero-action.jpg"],
    short: "Море безопасной пены, музыка и активные игры во дворе, на даче или турбазе.",
    description: "Привезём оборудование и устроим настоящее облако из пены. От площадки нужен доступ к электричеству; остальные детали мы подготовим сами.",
    includes: ["пенная установка", "ведущий", "музыка", "игры в пене"],
  },
  {
    id: "bubble-show",
    category: "shows",
    title: "Шоу мыльных пузырей",
    badge: "Для всей семьи",
    duration: "45–60 минут",
    price: null,
    image: "./public/media/bubbles.jpg",
    gallery: ["./public/media/bubbles.jpg", "./public/media/hero.jpg"],
    short: "Гигантские пузыри, спецэффекты и интерактив, в котором участвуют дети и взрослые.",
    description: "Лёгкое и зрелищное шоу можно провести как самостоятельную программу или добавить к празднику с аниматором.",
    includes: ["гигантские пузыри", "трюки и спецэффекты", "интерактив с гостями", "финальная фотосессия"],
  },
  {
    id: "cryo-show",
    category: "shows",
    title: "Крио-шоу",
    badge: "от 5 лет",
    duration: "45–60 минут",
    price: 7500,
    image: "./public/media/cryo.jpg",
    gallery: ["./public/media/cryo.jpg", "./public/media/neon.jpg"],
    short: "Научное шоу с густым туманом, заморозкой предметов и эффектными опытами.",
    description: "Ведущий в защитной экипировке показывает опыты с жидким азотом. Дети участвуют в безопасных заданиях и наблюдают за превращениями с близкого расстояния.",
    includes: ["ведущий-учёный", "оборудование и реквизит", "серия опытов", "безопасный интерактив"],
  },
  {
    id: "silver-disco",
    category: "shows",
    title: "Серебряная дискотека",
    badge: "Сияющий финал",
    duration: "по сценарию",
    price: null,
    image: "./public/media/silver-disco.jpg",
    gallery: ["./public/media/silver-disco.jpg", "./public/media/neon-show.jpg"],
    short: "Килограммы сияющей фольги, музыка и танцы внутри настоящего серебряного вихря.",
    description: "Серебряную дискотеку можно заказать отдельно или добавить ярким финалом к программе с персонажем.",
    includes: ["серебряная фольга", "ведущий", "музыка", "танцевальный интерактив"],
  },
  {
    id: "foam-blocks-show",
    category: "shows",
    title: "Поролоновое шоу",
    badge: "Детям и взрослым",
    duration: "по сценарию",
    price: null,
    image: "./public/media/foam-blocks.jpg",
    gallery: ["./public/media/foam-blocks.jpg", "./public/media/hero-action.jpg"],
    short: "Огромные мягкие кубики, активные игры и безопасное веселье для всей семьи.",
    description: "Командная программа с поролоновыми кубиками подходит для залов и открытых площадок.",
    includes: ["мягкий реквизит", "ведущий", "командные игры", "музыка"],
  },
  {
    id: "balloon-show",
    category: "shows",
    title: "Шоу шаров «Остров Надувляндия»",
    badge: "Путешествие",
    duration: "по сценарию",
    price: null,
    image: "./public/media/balloon-show.jpg",
    gallery: ["./public/media/balloon-show.jpg", "./public/media/animators.jpg"],
    short: "Приключение к сокровищам с волшебными шарами, играми, танцами и ведущими.",
    description: "Сюжетное семейное шоу превращает площадку в остров с заданиями, картой и воздушными открытиями.",
    includes: ["два ведущих", "шары и реквизит", "сюжетные игры", "танцы"],
  },
  {
    id: "water-battle",
    category: "shows",
    title: "Водная битва",
    badge: "Летний формат",
    duration: "по сценарию",
    price: null,
    image: "./public/media/water-battle.jpg",
    gallery: ["./public/media/water-battle.jpg", "./public/media/foam.jpg"],
    short: "Водные челленджи и игры, которые можно объединить с большой пенной вечеринкой.",
    description: "Активный летний формат для дней рождения, выпускных, лагерей и корпоративов на открытой площадке.",
    includes: ["водный реквизит", "ведущие", "командные испытания", "музыка"],
  },
  {
    id: "holi-colors",
    category: "shows",
    title: "Фестиваль красок Холи",
    badge: "Яркий финал",
    duration: "по сценарию",
    price: null,
    image: "./public/media/graduation.jpg",
    gallery: ["./public/media/graduation.jpg", "./public/media/hero-action.jpg"],
    short: "Безопасные фестивальные краски для общего цветного взрыва и эффектных фотографий.",
    description: "Холи можно добавить к выпускному, дню рождения, корпоративу или отдельной фестивальной программе.",
    includes: ["фестивальные краски", "ведущий", "музыкальный финал", "общая фотосессия"],
  },
  {
    id: "tesla-show",
    category: "shows",
    title: "Тесла-шоу",
    badge: "В составе пакета",
    duration: "по сценарию",
    price: null,
    image: "./public/media/graduation.jpg",
    gallery: ["./public/media/graduation.jpg", "./public/media/cryo.jpg"],
    short: "Молнии и электрические эффекты для научной кульминации большого праздника.",
    description: "Тесла-шоу указано в актуальном пакете выпускного как один из вариантов шоу на выбор. Детали программы подтвердит менеджер.",
    includes: ["электрические эффекты", "ведущий", "оборудование", "сценарная кульминация"],
  },
  {
    id: "graduation",
    category: "programs",
    title: "Выпускной «Красочный бум»",
    badge: "Готовый пакет",
    duration: "60 минут",
    price: 35000,
    image: "./public/media/graduation.jpg",
    gallery: ["./public/media/graduation.jpg", "./public/media/animators.jpg", "./public/media/hero.jpg"],
    short: "Два ведущих, диджей, профессиональный звук и фестивальные краски для всего класса.",
    description: "Готовая программа для яркого завершения учебного года. Динамику держат два ведущих, а финалом становится общий красочный взрыв.",
    includes: ["два ведущих", "диджей и звук", "индивидуальные наборы краски", "общий яркий финал"],
  },
  {
    id: "graduation-mega",
    category: "programs",
    title: "Выпускной «Мега-шоу»",
    badge: "Хит сезона",
    duration: "от 60 минут",
    price: 45000,
    image: "./public/media/graduation.jpg",
    gallery: ["./public/media/graduation.jpg", "./public/media/neon-show.jpg", "./public/media/cryo.jpg"],
    short: "Ведущие, диджей, краски Холи и одно большое шоу на выбор.",
    description: "Пакет включает всё из «Красочного бума» и одну кульминацию: Тесла, крио, серебряную неоновую дискотеку или поролоновое шоу.",
    includes: ["два ведущих и диджей", "фестивальные краски", "профессиональный звук", "одно шоу на выбор"],
  },
  {
    id: "hype-party",
    category: "programs",
    title: "«Хайп Туса»",
    badge: "7–14 лет",
    duration: "60 минут",
    price: null,
    image: "./public/media/hype-party.jpg",
    gallery: ["./public/media/hype-party.jpg", "./public/media/neon-show.jpg"],
    short: "Неоновая программа для школьников с диджеем, ведущими и трендовыми интерактивами.",
    description: "Сезонная программа для класса или большой компании. Актуальную доступность и состав подтвердит менеджер.",
    includes: ["неоновые ведущие", "диджей", "трендовые игры", "дискотека"],
  },
  {
    id: "santa-program",
    category: "programs",
    title: "Дед Мороз и Снегурочка",
    badge: "Зимний сезон",
    duration: "по сценарию",
    price: null,
    image: "./public/media/santa.jpg",
    gallery: ["./public/media/santa.jpg", "./public/media/hype-party.jpg"],
    short: "Домашнее поздравление, утренник или корпоративная программа с зимними героями.",
    description: "Подберём спокойный домашний визит или большую музыкальную программу для группы гостей.",
    includes: ["Дед Мороз", "Снегурочка", "игры и поздравление", "фотографии"],
  },
];

export const reviews = [
  {
    text: "Спасибо вам огромное за праздник — дочка очень рада!",
    context: "Детский день рождения",
    source: "Отзыв из Telegram-канала",
  },
  {
    text: "Дети с удовольствием участвовали в конкурсах и танцевали. Всем всё очень понравилось.",
    context: "Праздник с аниматорами",
    source: "Отзыв из Telegram-канала",
  },
  {
    text: "Спасибо огромное, вы — чудо. Мама очень счастлива и ещё долго будет вспоминать этот сюрприз.",
    context: "Поздравление с большим медведем",
    source: "Отзыв из Telegram-канала",
  },
  {
    text: "Всегда на связи, слышат и поддерживают любые идеи, создают атмосферу праздника за секунды.",
    context: "Сюрприз для подруги",
    source: "Видеоотзыв клиента",
  },
];

export const steps = [
  { number: "01", icon: "✦", title: "Выберите направление", text: "Аниматор, экспресс-поздравление, шоу или готовая программа." },
  { number: "02", icon: "+", title: "Соберите заявку", text: "Добавьте подходящих героев и шоу в одну корзину." },
  { number: "03", icon: "✓", title: "Уточним детали", text: "Проверим дату, место и подтвердим точную стоимость." },
];

export function getService(id) {
  return services.find((service) => service.id === id);
}
